/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.users;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.dreamflyer.hibernate.HibernateSessionFactory;
import com.dreamflyer.hibernate.SHibernateSessionFactory;
import com.dreamflyer.struts.form.users.ReloginForm;
import com.dreamflyer.user.SjtuStudent;

/** 
 * MyEclipse Struts
 * Creation date: 12-20-2008
 * 
 * XDoclet definition:
 * @struts.action path="/relogin" name="reloginForm" input="/form/relogin.jsp" scope="request" validate="true"
 */
public class ReloginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ReloginForm reloginForm = (ReloginForm) form;// TODO Auto-generated method stub
		String username = reloginForm.getUsername();
		String password = reloginForm.getPassword();
		try{
				
			Session ses = SHibernateSessionFactory.getSession();
			Transaction tx = ses.beginTransaction();
				
			String sqlquery = "from SjtuStudent a where a.id = '" +
							username +"'";
				
			Query  requery = ses.createQuery(sqlquery);
			ArrayList studentlist = (ArrayList)requery.list();
				
			tx.commit();
			ses.close();
			
			SjtuStudent student = new SjtuStudent();
						
			if(studentlist == null || studentlist.size() == 0){
				System.out.println("User name not exist!");
				return mapping.findForward("login_fail");
			}
			student = (SjtuStudent)studentlist.get(0);
					
			if(!password.equals(student.getPassword()))
			{
				System.out.println("Wrong Password!");
				return mapping.findForward("login_fail");
			}
					
			HttpSession session = request.getSession();
			SjtuStudent cur_user = (SjtuStudent)session.getAttribute("current_user");
					
			if(cur_user != null){
				session.removeAttribute("current_user");
			}
			session.setAttribute("current_user", student);
					
			return mapping.findForward("student_registry");
					
			}catch(Exception e){
				e.printStackTrace();
				return mapping.findForward("login_fail");
			}
	}
}
