/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.field;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.dreamflyer.fieldsystem.factory.Singleton;
import com.dreamflyer.fieldsystem.factory.Utility;
import com.dreamflyer.fieldsystem.interfaces.iManagerCreator;

/** 
 * MyEclipse Struts
 * Creation date: 12-14-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @author hujingfei
 */
public class ApplyAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if((Utility.isLogin(request)) == null )
			return mapping.findForward("error1");
		iManagerCreator factory = Singleton.getInstance("FieldManagerCreator");
		List list = factory.getManager().getFields();
		if(list == null )
			return mapping.findForward("error");
		request.setAttribute("flist", list);
		return mapping.findForward("applyF");
	}
}