/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.job;

import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dreamflyer.jobsystem.factory.JobSystemFactory;
import com.dreamflyer.jobsystem.interfaces.iJobManagerFactory;
import com.dreamflyer.jobsystem.interfaces.iManageJob;
import com.dreamflyer.struts.form.job.AddjobForm;
import com.dreamflyer.user.Company;

/** 
 * MyEclipse Struts
 * Creation date: 12-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/addjob" name="addjobForm" input="/addjob.jsp" scope="request" validate="true"
 * @struts.action-forward name="companyjob" path="/jobsystem/companyjob.jsp"
 */
public class AddjobAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddjobForm myform = (AddjobForm) form;
		HttpSession session = request.getSession();
		int companyid = 3;
		
		Company com;
		if(session==null){
			return mapping.findForward("login");
		}
		else{
			com = (Company)session.getAttribute("current_user");
			if(com==null){
				return mapping.findForward("login");
			}
		}
		companyid = com.getId();
		iJobManagerFactory f = JobSystemFactory.getManager();
		iManageJob manager = f.getManager();
		String sex,grade,subdate,other_requirements,description;
		int number,workyears,industry,function;
		sex = myform.getSex();
		grade = myform.getGrade();
		number = Integer.parseInt(myform.getNumber());
		workyears = Integer.parseInt(myform.getWorkyears());
		other_requirements = myform.getDemand();
		description = myform.getDescription();
		Calendar cal=Calendar.getInstance();
        cal.add(Calendar.DAY_OF_YEAR,-200);
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        subdate = sdf.format(cal.getTime());
        function = Integer.parseInt(myform.getFunctionid());
        industry = Integer.parseInt(myform.getIndustryid());
		
        try {
			sex = URLDecoder.decode(sex,"UTF-8");
			grade = URLDecoder.decode(grade,"UTF-8");
			other_requirements = URLDecoder.decode(other_requirements,"UTF-8");
			description = URLDecoder.decode(description,"UTF-8");
			//System.out.println("¹þ¹þ");
			//System.out.println(province);
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
        
		boolean result = manager.addJob(sex, grade, number, subdate, workyears, other_requirements, description, companyid, function, industry);
		if(result==true){
			List res = manager.getJob(companyid);
			request.setAttribute("jobresult", res);
			return mapping.findForward("companyjob");
		}
		return null;
	}
}