/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.job;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dreamflyer.jobsystem.factory.JobSystemFactory;
import com.dreamflyer.jobsystem.interfaces.iApplyJob;
import com.dreamflyer.jobsystem.interfaces.iJobApplyerFactory;
import com.dreamflyer.struts.form.job.GetfunctionForm;
import com.dreamflyer.struts.form.job.SearchjobForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-21-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="functionresult" path="/jobsystem/functionresult.jsp"
 */
public class GetfunctionAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetfunctionForm myform = (GetfunctionForm)form;
		response.setContentType("text/xml");
		
		iJobApplyerFactory f = JobSystemFactory.getApplyer();
		iApplyJob applyer = f.getApplyer();
		List result = applyer.getFunction(Long.parseLong(myform.getIndustryid()));
		try {
			StringBuffer buffer = new StringBuffer();
			buffer.append("<functions>");
			PrintWriter pw=response.getWriter();
			for(int i=0;i<result.size();i+=2){
				buffer.append("<function><id>");
				buffer.append(result.get(i));
				buffer.append("</id><name>");
				buffer.append(result.get(i+1));
				buffer.append("</name></function>");
			}
			buffer.append("</functions>");
			
			pw.print(buffer);
			
			pw.flush();
			pw.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}