/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.job;

import java.io.*;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dreamflyer.jobsystem.factory.JobSystemFactory;
import com.dreamflyer.jobsystem.interfaces.iApplyJob;
import com.dreamflyer.jobsystem.interfaces.iJobApplyerFactory;
import com.dreamflyer.struts.form.job.SearchjobForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-21-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="industryresult" path="/jobsystem/industryresult.jsp"
 */
public class GetindustryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("text/xml;charset=utf-8");
		SearchjobForm myform = (SearchjobForm) form;
		iJobApplyerFactory f = JobSystemFactory.getApplyer();
		iApplyJob applyer = f.getApplyer();
		//System.out.println("haha1");
		List result = applyer.getIndustry();
		//System.out.println("haha2");
		try {
			StringBuffer buffer = new StringBuffer();
			buffer.append("<industries>");
			PrintWriter pw=response.getWriter();
			for(int i=0;i<result.size();i+=2){
				buffer.append("<industry><id>");
				buffer.append(result.get(i));
				buffer.append("</id><name>");
				buffer.append(result.get(i+1));
				buffer.append("</name></industry>");
			}
			buffer.append("</industries>");
			
			pw.print(buffer.toString());
			//System.out.println(buffer.toString());
			pw.flush();
			pw.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}