/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.dreamflyer.struts.form.HuntJobForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-16-2008
 * 
 * XDoclet definition:
 * @struts.action path="/huntJob" name="huntJobForm" input="/form/huntJob.jsp" scope="request" validate="true"
 */
public class HuntJobAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HuntJobForm huntJobForm = (HuntJobForm) form;// TODO Auto-generated method stub
		return null;
	}
}