/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.job;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dreamflyer.jobsystem.factory.JobSystemFactory;
import com.dreamflyer.jobsystem.interfaces.iJobManagerFactory;
import com.dreamflyer.jobsystem.interfaces.iManageJob;
import com.dreamflyer.struts.form.job.GetapplyerForm;
import com.dreamflyer.user.Company;

/** 
 * MyEclipse Struts
 * Creation date: 12-23-2008
 * 
 * XDoclet definition:
 * @struts.action path="/getapplyer" name="getapplyerForm" input="/getApplyer.jsp" scope="request" validate="true"
 * @struts.action-forward name="applyerresult" path="/jobsystem/applyerresult.jsp"
 */
public class GetapplyerAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//System.out.println("I have reach action");
		HttpSession session = request.getSession();
		int companyid = 3;
		
		Company com;
		if(session==null){
			return mapping.findForward("login");
		}
		else{
			com = (Company)session.getAttribute("current_user");
			if(com==null){
				return mapping.findForward("login");
			}
		}
		GetapplyerForm myform = (GetapplyerForm) form;
		iJobManagerFactory f = JobSystemFactory.getManager();
		iManageJob manager = f.getManager();
		long jobid = Integer.parseInt(myform.getJobid());
		List result = manager.getApplyers(jobid);
		request.setAttribute("applyerresult", result);
		//System.out.println("I have get the list");
		//System.out.println("List size:"+result);
		return mapping.findForward("applyerresult");
	}
}