/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dreamflyer.struts.action.job;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dreamflyer.jobsystem.factory.JobSystemFactory;
import com.dreamflyer.jobsystem.interfaces.iJobApplyerFactory;
import com.dreamflyer.jobsystem.interfaces.iJobManagerFactory;
import com.dreamflyer.jobsystem.interfaces.iManageJob;
import com.dreamflyer.user.Company;

/** 
 * MyEclipse Struts
 * Creation date: 12-23-2008
 * 
 * XDoclet definition:
 * @struts.action input="/getApplyer.jsp" validate="true"
 */
public class GetcompanyjobAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("text/xml;charset=utf-8");
		HttpSession session = request.getSession();
		int companyid = 3;
		/*
		Company com;
		if(session==null){
			return null;
		}
		else{
			com = (Company)session.getAttribute("currentcom");
			if(com==null){
				return null;
			}
		}
		*/
		iJobManagerFactory f = JobSystemFactory.getManager();
		iManageJob manager = f.getManager();
		List result = manager.getJob(companyid);
		StringBuffer buffer = new StringBuffer();
		try {
			
			buffer.append("<jobs>");
			PrintWriter pw=response.getWriter();
			for(int i=0;i<result.size();i+=2){
				buffer.append("<job><id>");
				buffer.append(result.get(i));
				buffer.append("</id><name>");
				buffer.append(result.get(i+1));
				buffer.append("</name></job>");
			}
			buffer.append("</jobs>");
			
			pw.print(buffer.toString());
			//System.out.println(buffer.toString());
			pw.flush();
			pw.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	 return null;
	}
}